server:
  port: 1111
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri:
          clone-on-start: true
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka